"use client";
import { motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Circle } from "lucide-react";
export default function Hero(){return <section id="work" className="relative min-h-screen overflow-hidden px-5 pt-28 sm:px-8"><div className="mx-auto grid min-h-[calc(100vh-7rem)] max-w-6xl items-center gap-10 lg:grid-cols-[1.2fr_.8fr]"><div>
<div className="mb-8 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.22em] text-white/40"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_18px_rgba(52,211,153,.8)]"/><span>Available for internships / freelance</span></div>
<p className="font-mono text-sm text-fuchsia-300/80">NURA / DEVELOPER + SECURITY LEARNER</p>
<motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="mt-4 max-w-5xl text-[clamp(4rem,10vw,9rem)] font-black leading-[.82] tracking-[-.07em]">BUILD<br/><span className="text-white/25">THINGS.</span></motion.h1>
<p className="mt-8 max-w-2xl text-lg leading-8 text-white/60">I design and build useful software, automation, and experiments while moving deeper into cybersecurity.</p>
<div className="mt-8 flex flex-wrap gap-3"><a href="#projects" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-black">Explore work <ArrowDownRight size={15}/></a><a href="/resume.pdf" download className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.03] px-5 py-3 text-sm text-white/70 hover:text-white">Resume <ArrowUpRight size={15}/></a></div>
</div><div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-8 rounded-[2rem] bg-fuchsia-500/10 blur-3xl"/><div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.03] p-2 shadow-2xl"><div className="relative aspect-[4/5] overflow-hidden rounded-[1.6rem] bg-black"><img src="/myprofilepicforportfolio.png" alt="Nura" className="h-full w-full object-cover grayscale contrast-110 mix-blend-screen opacity-90"/><div className="absolute inset-0 bg-[linear-gradient(135deg,transparent_0%,rgba(217,70,239,.08)_38%,transparent_72%)]"/><div className="absolute left-4 right-4 top-4 flex justify-between font-mono text-[9px] uppercase tracking-[.22em] text-white/50"><span>PORTRAIT / 001</span><span>EST. 2022</span></div><div className="absolute bottom-4 left-4 font-mono text-[9px] uppercase tracking-[.2em] text-white/50">SYSTEMS / WEB / AUTOMATION</div></div></div><div className="mt-3 flex items-center justify-between font-mono text-[10px] uppercase tracking-[.2em] text-white/30"><span>Creative technologist</span><span className="flex items-center gap-2"><Circle size={8} fill="currentColor"/> scroll to inspect</span></div></div></div>
<div className="absolute bottom-6 left-5 right-5 mx-auto flex max-w-6xl items-center justify-between font-mono text-[10px] uppercase tracking-[.18em] text-white/25"><span>01 / 04</span><span>Chennai, India</span></div></div></section>}
