"use client";
import { motion } from "framer-motion";import { ArrowUpRight, Github } from "lucide-react";
const projects=[
{name:"FIRO",type:"Product / Web",desc:"Expense management web app built around a practical room-sharing workflow.",tech:["React","MySQL","TypeScript"],image:"/projects/Firo.png",live:"https://firo-two.vercel.app",github:"https://github.com/Nura730/FIRO"},
{name:"Nura OS",type:"Personal System",desc:"A personal tracking and productivity system combining tasks, expenses, and AI-assisted workflows.",tech:["React","MySQL","JavaScript"],image:"/projects/nuraos.png",live:"https://nuraos-beta.vercel.app",github:"https://github.com/Nura730/Nura_OS"},
{name:"Log Management System",type:"Automation",desc:"Team operations system connecting attendance, tasks, chat, and automated reminders.",tech:["Apps Script","n8n","JavaScript"],image:"/projects/logsystem.png",live:"https://invodes-log-system.vercel.app",github:"https://github.com/Nura730/Invodes-Log-System"},
{name:"Naval Portfolio",type:"Client Work",desc:"A focused portfolio experience designed for a marine student.",tech:["HTML","Tailwind","JavaScript"],image:"/projects/naval.png",live:"https://sasikumar-naval-portfolio.netlify.app",github:"https://github.com/Nura730/naval-portfolio"},
];
export default function Projects(){return <section id="projects" className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-6xl"><div className="mb-12 flex items-end justify-between gap-6"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-fuchsia-300/70">03 / Selected work</p><h2 className="mt-3 text-4xl font-bold tracking-tight sm:text-6xl">Built, not claimed.</h2></div><span className="hidden font-mono text-[10px] uppercase tracking-[.2em] text-white/25 md:block">case studies / selected</span></div><div className="space-y-8">{projects.map((p,i)=><motion.article key={p.name} initial={{opacity:0,y:32}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.6,delay:i*.05}} className="group grid overflow-hidden rounded-[1.75rem] border border-white/10 bg-white/[.025] lg:grid-cols-[1.15fr_.85fr]"><a href={p.live} target="_blank" rel="noreferrer" className="relative min-h-72 overflow-hidden border-b border-white/10 bg-black lg:border-b-0 lg:border-r"><img src={p.image} alt={p.name} className="h-full w-full object-cover opacity-80 grayscale transition duration-700 group-hover:scale-[1.03] group-hover:opacity-100 group-hover:grayscale-0"/><div className="absolute left-5 top-5 rounded-full border border-white/10 bg-black/60 px-3 py-1 font-mono text-[9px] uppercase tracking-[.18em] text-white/60">{p.type}</div></a><div className="flex flex-col justify-between p-7 sm:p-9"><div><div className="font-mono text-[10px] text-white/25">0{i+1}</div><h3 className="mt-4 text-3xl font-semibold tracking-tight">{p.name}</h3><p className="mt-4 max-w-md text-sm leading-7 text-white/50">{p.desc}</p><div className="mt-6 flex flex-wrap gap-2">{p.tech.map(t=><span key={t} className="rounded-full border border-white/10 px-2.5 py-1 font-mono text-[9px] uppercase tracking-[.12em] text-white/40">{t}</span>)}</div></div><div className="mt-10 flex items-center gap-5 text-sm"><a href={p.live} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-white hover:text-fuchsia-300">Live <ArrowUpRight size={14}/></a><a href={p.github} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-white/45 hover:text-white">Source <Github size={14}/></a></div></div></motion.article>)}</div></div></section>}
